# Generated by Django 2.0.4 on 2018-04-27 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_long_position', models.DecimalField(decimal_places=5, max_digits=8)),
                ('from_lat_position', models.DecimalField(decimal_places=5, max_digits=8)),
                ('to_long_position', models.DecimalField(decimal_places=5, max_digits=8)),
                ('to_lat_position', models.DecimalField(decimal_places=5, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('wait', 'waiting'), ('start', 'in ride'), ('end', 'completed')], default='wait', max_length=5)),
                ('distance', models.FloatField(default=2.0)),
                ('fair', models.FloatField(default=16.0)),
            ],
        ),
        migrations.CreateModel(
            name='RiderBookingTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Booking')),
            ],
        ),
    ]
