# Generated by Django 2.0.4 on 2018-04-27 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderbookingtable',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Rider'),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Driver'),
        ),
        migrations.AddField(
            model_name='booking',
            name='rider',
            field=models.ManyToManyField(through='booking.RiderBookingTable', to='registration.Rider'),
        ),
    ]
