# Generated by Django 2.0.4 on 2018-04-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20180427_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='distance',
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name='booking',
            name='fair',
            field=models.FloatField(default=16.0),
        ),
    ]
