# Generated by Django 2.0.4 on 2018-04-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lat_position',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='long_position',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True),
        ),
    ]
